# Clock and reset
create_clock -period 10.000 -name clk_100MHz -waveform {0.000 5.000} [get_ports clk_100MHz]
set_property IOSTANDARD LVCMOS33 [get_ports clk_100MHz]
set_property PACKAGE_PIN N15 [get_ports clk_100MHz]

set_property IOSTANDARD LVCMOS25 [get_ports reset_n]
set_property PACKAGE_PIN J2 [get_ports reset_n]

# Image selection pins (switches)
set_property IOSTANDARD LVCMOS25 [get_ports {image_select[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {image_select[1]}]
set_property PACKAGE_PIN G1 [get_ports {image_select[0]}]
set_property PACKAGE_PIN K2 [get_ports {image_select[1]}]

# HDMI Output Pins
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_clk]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_hsync]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_vsync]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_active]
set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_red[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_red[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_red[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_red[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_green[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_green[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_green[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_green[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_blue[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_blue[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_blue[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_blue[3]}]

# HDMI pin assignments (reusing from shape_detector_system.xdc)
set_property PACKAGE_PIN V17 [get_ports hdmi_clk]
set_property PACKAGE_PIN U16 [get_ports hdmi_hsync]
set_property PACKAGE_PIN U18 [get_ports hdmi_vsync]
set_property PACKAGE_PIN R17 [get_ports hdmi_active]
set_property PACKAGE_PIN T14 [get_ports {hdmi_red[0]}]
set_property PACKAGE_PIN U17 [get_ports {hdmi_red[1]}]
set_property PACKAGE_PIN R16 [get_ports {hdmi_red[2]}]
set_property PACKAGE_PIN R14 [get_ports {hdmi_red[3]}]
set_property PACKAGE_PIN T14 [get_ports {hdmi_green[0]}]
set_property PACKAGE_PIN U17 [get_ports {hdmi_green[1]}]
set_property PACKAGE_PIN R16 [get_ports {hdmi_green[2]}]
set_property PACKAGE_PIN R14 [get_ports {hdmi_green[3]}]
set_property PACKAGE_PIN T14 [get_ports {hdmi_blue[0]}]
set_property PACKAGE_PIN U17 [get_ports {hdmi_blue[1]}]
set_property PACKAGE_PIN R16 [get_ports {hdmi_blue[2]}]
set_property PACKAGE_PIN R14 [get_ports {hdmi_blue[3]}] 